# Generated by Django 4.0.2 on 2022-02-10 15:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maze_makr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maze',
            name='maze',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(), size=None),
        ),
    ]
