# Generated by Django 4.0.2 on 2022-02-11 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maze_makr', '0007_alter_maze_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maze',
            name='user',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mazes', to='maze_makr.user'),
        ),
    ]
