# Generated by Django 4.0.2 on 2022-02-10 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maze_makr', '0002_alter_maze_maze'),
    ]

    operations = [
        migrations.AddField(
            model_name='maze',
            name='height',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='maze',
            name='width',
            field=models.IntegerField(default=3),
        ),
    ]
