# Generated by Django 4.0.2 on 2022-02-10 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maze_makr', '0003_maze_height_maze_width'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
