# Generated by Django 4.0.2 on 2022-02-11 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maze_makr', '0004_user_maze_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maze',
            old_name='username',
            new_name='user',
        ),
    ]
