# Generated by Django 4.0.2 on 2022-02-10 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maze_makr', '0005_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
